# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
dist: trusty
env:
  global:
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
notifications:
  email: false
r_packages:
  - auditor
  - archivist
  - covr
  - ranger
  - testthat
  - DALEX
  - devtools
  - breakDown

r_github_packages:
  - ModelOriented/ceterisParibus2
  - ModelOriented/drifter

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev

after_success:
  - Rscript -e 'library(covr); codecov()'

