# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
dist: trusty
env:
  global:
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
notifications:
  email: false
r_packages:
  - covr
  - ranger
  - testthat
  - DALEX

after_success:
  - Rscript -e 'library(covr); codecov()'

