# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
os:
  - linux
  - osx

r: release

env:
  global:
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings --as-cran --run-donttest"
notifications:
  email: false
r_packages:
  - auditor
  - archivist
  - covr
  - ranger
  - testthat
  - DALEX
  - devtools
  - breakDown
  - drifter

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev

after_success:
  - Rscript -e 'library(covr); codecov()'

